##NumPy Basics

##Orange yielding based on climatic conditions (temperature,rainfall,humidity)

data of climatic conditions in various places

In [ ]:
import math

In [ ]:
Kochi = [73,67,43]
Hyderabad = [91,88,64]
Chennai = [87,134,58]
Bangalore = [102,43,37]
Mumbai = [69,96,70]

weights

In [ ]:
w1,w2,w3 = 0.3,0.2,0.5

weights = [w1,w2,w3]

Function to calculate the crop yield

In [ ]:
%%time
def crop_yield(region,weights):
  result = 0
  for x,w in zip(region,weights):
    result += x*w
  return math.ceil((result))

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


In [ ]:
crop_yield(Kochi,weights)

57

****************************************************************************************************************************************************************

##Now consider same concept using NumPy

In [ ]:
import numpy as np

In [ ]:
Kochi= np.array([73,67,43])
Hyderabad = np.array([91,88,64])
Chennai = np.array([87,134,58])
Bangalore = np.array([102,43,37])
Mumbai = np.array([69,96,70])

In [ ]:
w1,w2,w3 = 0.3,0.2,0.5

weights = np.array([w1,w2,w3])

In [ ]:
weights

array([0.3, 0.2, 0.5])

In [ ]:
(Kochi * weights).sum()

56.8

In [ ]:
%%time
np.dot(Kochi,weights).sum()

CPU times: user 92 µs, sys: 12 µs, total: 104 µs
Wall time: 97.5 µs


56.8

****************************************************************************************************************************************************************

 Calculate Orange yield based on soil pH, sunlight hours, and irrigation frequency.

data at different places

In [ ]:
import math

In [ ]:
Kochi = [45,63,27]
Hyderabad = [43,88,23]
Chennai = [87,134,35]
Bangalore = [102,43,46]
Mumbai = [69,96,50]

In [ ]:
w1,w2,w3 = 0.2,0.4,0.7

weights = [w1,w2,w3]

In [ ]:
def orange_yield(region,weights):
  result = 0
  for x,w in zip(region,weights):
    result += x*w
    return math.ceil((result))

Try Determine Wheat yield based on temperature, soil moisture, and fertilizer usage.

***********************************************************************************************************************************************************************************************

##Numpy array representation

In [ ]:
Climate_data = np.array ([[45,63,27],
                          [43,88,23],
                          [87,134,35],
                          [102,43,46],
                          [69,96,50]])


In [ ]:
np.reshape(Climate_data,(3,5))

array([[ 45,  63,  27,  43,  88],
       [ 23,  87, 134,  35, 102],
       [ 43,  46,  69,  96,  50]])

length of the dimension

In [ ]:
Climate_data.shape

(5, 3)

In [ ]:
Climate_datas = np.array ([[[45,63,27],
                          [43,88,23,]],

                          [
                          [102,43,46],
                          [69,96,50]]])


In [ ]:
Climate_datas.shape

(2, 2, 3)

****************************************************************************************************************************************************************

#finding the same orange yield using numpy functions

In [ ]:
new_Climate_data = np.array([[73,67,43],
                             [91,88,64],
                             [87,134,58],
                             [102,43,37],
                             [69,96,70]])

In [ ]:
weights = np.array([w1,w2,w3])

In [ ]:
 np.matmul(new_Climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
np.dot(new_Climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [ ]:
Orange_yield = new_Climate_data @ weights

********************************************************************************************************************************************************************************************************************************************************************************************************************************

#Trying this problem in real code environment

In [ ]:
import os

In [ ]:
#filename = "climate.csv"
txt_filename = "climate.txt"

#os.rename(filename,txtfilename)


climate_data = np.genfromtxt(txt_filename, delimiter=',', skip_header=1)


In [ ]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [ ]:
climate_data.shape

(10000, 3)

In [ ]:
weights = np.array([0.3,0.2,0.5])

In [ ]:
orange_yield = climate_data @ weights

In [ ]:
orange_yield

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [ ]:
orange_yield.shape

(10000,)

In [ ]:
climate_result = np.concatenate((climate_data,orange_yield.reshape(10000,1)),axis=1)

In [ ]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [ ]:
np.savetxt("climate_results.txt",climate_result, fmt='%.2f', header=' soil_pH, sunlight_hours,irrigation_frequency,orange_yield',comments="")

****************************************************************************************************************************************************************

##Array indexing and slicing

In [ ]:
 arr3 = np.array([[[11,12,13,14],
                  [13,14,15,19]],

                  [[15,16,17,21],
                  [63,92,36,18]],

                  [[98,32,81,23],
                  [17,18,19.5,43]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
arr3[1,1,2]

36.0

In [ ]:
arr3[2,0,3]

23.0

Range

In [ ]:
arr3[1:,0:1,:2]

array([[[15., 16.]],

       [[98., 32.]]])

In [ ]:
arr3[0:2,0:1,2:]

array([[[13., 14.]],

       [[17., 21.]]])

Indices and range

In [ ]:
arr3[1:,1,2]

array([36. , 19.5])

##Different ways to create Numpy

In [ ]:
#all zeros
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#all ones
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#identity matrix(diagonal)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#random vector
np.random.rand(7)

array([0.25464513, 0.22917186, 0.2660235 , 0.30956083, 0.91123116,
       0.71507391, 0.97173843])

In [ ]:
#random matrix
np.random.randn(6,2)

array([[-1.00055514, -0.57297138],
       [-0.58516891,  0.03673877],
       [ 0.6955743 , -0.35646852],
       [-0.22729325, -0.0149967 ],
       [ 1.02140723, -1.3785221 ],
       [-0.38100414,  0.71311363]])

In [ ]:
#fixed value
np.full([3,3],4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
#range with start,end and step
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [ ]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [ ]:
np.linspace(4,50,20)

array([ 4.        ,  6.42105263,  8.84210526, 11.26315789, 13.68421053,
       16.10526316, 18.52631579, 20.94736842, 23.36842105, 25.78947368,
       28.21052632, 30.63157895, 33.05263158, 35.47368421, 37.89473684,
       40.31578947, 42.73684211, 45.15789474, 47.57894737, 50.        ])